image: $IMAGE_REPOSITORY_URL/node:$CI_COMMIT_BRANCH

default:
  tags:
    - k8s-small-generic

cache:
  paths:
    - build/*

variables:
  REACT_APP_BACK_API_URL: /api/back

stages:
  - build
  - test
  - deploy
  - release

build:
  stage: build
  script:
    - echo "Build"
    - npm install
    - npm audit fix
    - CI=false npm run build
  rules:
    - if: ('$CI_COMMIT_BRANCH =~ /^($STANDARD_CD_BRANCHES)$/' || '$CI_COMMIT_BRANCH =~ /^($PROTECTED_CD_BRANCHES)$/') && $ONLY_RELEASE == null
    - when: never

test:
  stage: test
  script:
    - echo "Testing the code"
#    -
  rules:
    - if: ('$CI_COMMIT_BRANCH =~ /^($STANDARD_CD_BRANCHES)$/' || '$CI_COMMIT_BRANCH =~ /^($PROTECTED_CD_BRANCHES)$/') && $ONLY_RELEASE == null
    - when: never

deploy:
  image :
    name : $IMAGE_REPOSITORY_URL/kaniko-executor:$CI_COMMIT_BRANCH
    entrypoint : [ "" ]
  stage: deploy
  script:
    - sh .gitlab/deployment.sh
  rules:
    - if: ('$CI_COMMIT_BRANCH =~ /^($STANDARD_CD_BRANCHES)$/' || '$CI_COMMIT_BRANCH =~ /^($PROTECTED_CD_BRANCHES)$/') && $ONLY_RELEASE == null
    - when: never

release:
  image:
    name: $IMAGE_REPOSITORY_URL/alpine:$CI_COMMIT_BRANCH
    entrypoint: [ "" ]
  stage: release
  script:
    - bash .gitlab/release.sh
  rules:
    - if: ('$CI_COMMIT_BRANCH =~ /^($STANDARD_CD_BRANCHES)$/') && $ENABLE_RELEASE == "true"
    - if: ('$CI_COMMIT_BRANCH =~ /^($PROTECTED_CD_BRANCHES)$/') && $ENABLE_RELEASE == "true"
      when: manual
    - when: never