stages: # List of stages for jobs in their order of execution
  - lint
  - dependency-check
  - build
  - deploy

# this indicate this pipeline is active only for merge requests or some other rules (when the deploy is done)
# also this enable the merge request pipeline : https://docs.gitlab.com/ee/ci/pipelines/merge_request_pipelines.html#prerequisites
# pipelines are now only run when a merge request exists (it was initially put in place to allow the use of the commit lint based on the MR title)
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ /^feat_deploy_(\w*|\d*|-*)+$/ || $CI_COMMIT_BRANCH =~ /^release_(\w*|\d*|-*|_*|\.*)+$/

lint-job:
  stage: lint
  image: harbor.eds.aphp.fr/cohort360/commitlint:latest
  script:
    - echo "${CI_MERGE_REQUEST_TITLE}" | npx commitlint
  rules:
    # only run for the merge request pipeline
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

dependency-check-job:
  stage: dependency-check
  image:
    name: harbor.eds.aphp.fr/cohort360/dependency-check
    entrypoint: [ "" ]
  script:
    # See https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html
    - /usr/share/dependency-check/bin/dependency-check.sh --project Portail --proxyserver $HOST_PROXY --proxyport $PORT_PROXY  --disableOssIndex --out . --scan . --failOnCVSS 7 --noupdate
  artifacts:
    paths:
      - dependency-check-report.html
  allow_failure: true
  rules:
    # only run for the merge request and main pipelines
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == "main"

build-job:
  image: node:16.13.2
  stage: build
  script:
    - npm install
    - CI=false npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 day
  cache:
    key: cohort360_nodemodules_cache
    paths:
      - node_modules/
    policy: pull

deploy-job:
  image: gcr.io/kaniko-project/executor:debug
  stage: deploy
  needs:
    - job: build-job
      artifacts: true
  script:
    - export VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${BOT_NAME}\",\"password\":\"${BOT_TOKEN}\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context ${CI_PROJECT_DIR}
      --dockerfile ${CI_PROJECT_DIR}/Dockerfile
      --destination ${CI_REGISTRY_IMAGE}:${VERSION}
  rules:
    # this only builds when not a merge request event
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: always
