image: $HARBOR_REPOSITORY_URL/node:$CI_COMMIT_BRANCH

# uncomment when cache will be made available for kube shared runner
#default:
#  tags:
#    - k8s-small-generic

#cache:
#  paths:
#    - build/*

variables:
  REACT_APP_BACK_API_URL: /api/back

stages:
  - build
  - test
  - deploy
  - release

build:
  stage: build
  script:
    - echo "Build"
    - npm install
    - npm audit fix
    - CI=false npm run build
  rules:
    - if: ($CI_COMMIT_BRANCH == "fakedata" || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "qualif" || $CI_COMMIT_BRANCH == "prod_a" || $CI_COMMIT_BRANCH == "prod_b") && $ONLY_RELEASE == null
    - when: never

test:
  stage: test
  script:
    - echo "Testing the code"
#    -
  rules:
    - if: ($CI_COMMIT_BRANCH == "fakedata" || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "qualif" || $CI_COMMIT_BRANCH == "prod_a" || $CI_COMMIT_BRANCH == "prod_b") && $ONLY_RELEASE == null
    - when: never

deploy:
  image :
    name : $HARBOR_REPOSITORY_URL/kaniko-executor:$CI_COMMIT_BRANCH
    entrypoint : [ "" ]
  stage: deploy
  script:
    - sh .gitlab/deployment.sh
  rules:
    - if: ($CI_COMMIT_BRANCH == "fakedata" || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "qualif" || $CI_COMMIT_BRANCH == "prod_a" || $CI_COMMIT_BRANCH == "prod_b") && $ONLY_RELEASE == null
    - when: never

release:
  image:
    name: harbor.eds.aphp.fr/cohort360/kubectl:$CI_COMMIT_BRANCH
    entrypoint: [ "" ]
  stage: release
  script:
    - SUFFIX="-portail"
    - mkdir /root/.kube
    - cat $KUBE_CONFIG > /root/.kube/config
    - ENVIRONMENT=${CI_COMMIT_BRANCH/_/-}
    - kubectl rollout restart deployment/$ENVIRONMENT$SUFFIX
  rules:
    - if: $CI_COMMIT_BRANCH == "fakedata" || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "qualif"
    - if: $CI_COMMIT_BRANCH == "prod_a" || $CI_COMMIT_BRANCH == "prod_b"
      when: manual
    - when: never