stages: # List of stages for jobs in their order of execution
  - build
  - deploy

build-job:
  image: node:16.13.2
  stage: build
  script:
    - npm install
    - CI=false npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 day
  only:
    - tags
    - develop
    - /^feat_deploy_(\w*|\d*|-*)+$/
  cache:
    key: cohort360_nodemodules_cache
    paths:
      - node_modules/
    policy: pull

deploy-job:
  image: gcr.io/kaniko-project/executor:debug
  stage: deploy
  needs:
    - job: build-job
      artifacts: true
  script:
    - export VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
    - mkdir -p /kaniko/.docker
    - |-
      KANIKOPROXYARGS=""
      KANIKOCFG="\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${BOT_NAME}\",\"password\":\"${BOT_TOKEN}\"}}"
      if [ "x${http_proxy}" != "x" -o "x${https_proxy}" != "x" ]; then
        KANIKOCFG="${KANIKOCFG}, \"proxies\" : { \"default\" : { \"httpProxy\" : \"${http_proxy}\", \"httpsProxy\" : \"${https_proxy}\", \"noProxy\" : \"${no_proxy}\" } }"
        KANIKOPROXYARGS="--build-arg http_proxy=${http_proxy} --build-arg https_proxy=${https_proxy} --build-arg no_proxy=${no_proxy}"
      fi
      KANIKOCFG="{ ${KANIKOCFG} }"
      echo "${KANIKOCFG}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      $KANIKOPROXYARGS
      --destination "${CI_REGISTRY_IMAGE}:${VERSION}"
  only:
    - tags
    - develop
    - /^feat_deploy_(\w*|\d*|-*)+$/