image: $HARBOR_REPOSITORY_URL/node:14.6.0

cache:
  paths:
    - build/*

variables:
  REACT_APP_PORTAIL_API_URL: /api/portail
  REACT_APP_CONTEXT: aphp

default:
  tags:
    - k8s-small-generic

stages:
  - build
  - test
  - deploy
  - release

build:
  stage: build
  script:
    - echo "Build"
    - npm install
    - npm audit fix
    - npm run build

test:
  stage: test
  script:
    - echo "Testing the code"
#    -

deploy-to-fakedata:
  image :
    name : $HARBOR_REPOSITORY_URL/kaniko-executor:debug
    entrypoint : [ "" ]
  stage: deploy
  variables:
    ENVIR: "fakedata"
  script:
    - echo "{\"auths\":{\"$HARBOR_REGISTRY\":{\"username\":\"$BOT_NAME\",\"password\":\"$BOT_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $HARBOR_REPOSITORY_URL/cohort-portail:$ENVIR
  rules:
    - if: $CI_COMMIT_BRANCH == "fakedata"
    - when: never

deploy-to-dev:
  image :
    name : $HARBOR_REPOSITORY_URL/kaniko-executor:debug
    entrypoint : [ "" ]
  stage: deploy
  variables:
    ENVIR: "dev"
  script:
    - echo "{\"auths\":{\"$HARBOR_REGISTRY\":{\"username\":\"$BOT_NAME\",\"password\":\"$BOT_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $HARBOR_REPOSITORY_URL/cohort-portail:$ENVIR
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - when: never

deploy-to-staging:
  image :
    name : $HARBOR_REPOSITORY_URL/kaniko-executor:debug
    entrypoint : [ "" ]
  stage: deploy
  variables:
    ENVIR: "qualif"
  script:
    - echo "{\"auths\":{\"$HARBOR_REGISTRY\":{\"username\":\"$BOT_NAME\",\"password\":\"$BOT_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $HARBOR_REPOSITORY_URL/cohort-portail:$ENVIR
  rules:
    - if: $CI_COMMIT_BRANCH == "qualif"
    - when: never

release:
  image:
    name: harbor.eds.aphp.fr/cohort360/kubectl:latest
    entrypoint: [ "" ]
  stage: release
  variables:
    SUFFIX: "-portail"
  script:
    - echo $KUBE_CONFIG > /root/.kube/config
    - kubectl rollout restart deployment/$CI_COMMIT_BRANCH$SUFFIX
  rules:
    - if: $CI_COMMIT_BRANCH == "fakedata" || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "qualif"
    - if: $CI_COMMIT_BRANCH == "prod_a" || $CI_COMMIT_BRANCH == "prod_b"
      when: manual
    - when: never