image: $HARBOR_REPOSITORY_URL/node:$CI_COMMIT_BRANCH

# uncomment when cache will be made available for kube shared runner
#default:
#  tags:
#    - k8s-small-generic

cache:
  paths:
    - build/*

variables:
  REACT_APP_BACK_API_URL: /api/back

stages:
  - build
  - test
  - deploy
  - release

build:
  stage: build
  script:
    - echo "Build"
    - npm install
    - npm audit fix
    - npm run build

test:
  stage: test
  script:
    - echo "Testing the code"
#    -

deploy-to-fakedata:
  image :
    name : $HARBOR_REPOSITORY_URL/kaniko-executor:$CI_COMMIT_BRANCH
    entrypoint : [ "" ]
  stage: deploy
  variables:
    ENVIR: "fakedata"
    ENVIRONMENT: "fakedata"
  script:
    - sh .gitlab/ci/deployment.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "fakedata"
    - when: never

deploy-to-dev:
  image :
    name : $HARBOR_REPOSITORY_URL/kaniko-executor:$CI_COMMIT_BRANCH
    entrypoint : [ "" ]
  stage: deploy
  variables:
    ENVIR: "dev"
    ENVIRONMENT: "dev"
  script:
    - sh .gitlab/ci/deployment.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - when: never

deploy-to-staging:
  image :
    name : $HARBOR_REPOSITORY_URL/kaniko-executor:$CI_COMMIT_BRANCH
    entrypoint : [ "" ]
  stage: deploy
  variables:
    ENVIR: "qualif"
    ENVIRONMENT: "qualif"
  script:
    - sh .gitlab/ci/deployment.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "qualif"
    - when: never

deploy-to-prod-a:
  image :
    name : $HARBOR_REPOSITORY_URL/kaniko-executor:$CI_COMMIT_BRANCH
    entrypoint : [ "" ]
  stage: deploy
  variables:
    ENVIR: "prod_a"
    ENVIRONMENT: "prod-a"
  script:
    - sh .gitlab/ci/deployment.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "prod_a"
    - when: never

deploy-to-prod-b:
  image :
    name : $HARBOR_REPOSITORY_URL/kaniko-executor:$CI_COMMIT_BRANCH
    entrypoint : [ "" ]
  stage: deploy
  variables:
    ENVIR: "prod_b"
    ENVIRONMENT: "prod-b"
  script:
    - sh .gitlab/ci/deployment.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "prod_b"
    - when: never

release:
  image:
    name: harbor.eds.aphp.fr/cohort360/kubectl:$CI_COMMIT_BRANCH
    entrypoint: [ "" ]
  stage: release
  variables:
    SUFFIX: "-portail"
  script:
    - ENVIRONMENT=${CI_COMMIT_BRANCH/_/-}
    - kubectl rollout restart deployment/$ENVIRONMENT$SUFFIX
  rules:
    - if: $CI_COMMIT_BRANCH == "fakedata" || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "qualif"
    - if: $CI_COMMIT_BRANCH == "prod_a" || $CI_COMMIT_BRANCH == "prod_b"
      when: manual
    - when: never