FROM harbor.eds.aphp.fr/cohort360/node:{{ENVIR}}
WORKDIR /root
COPY ./ ./
RUN mkdir -p /etc/nginx && mkdir -p /etc/nginx/sites-enabled/
COPY nginx.conf /etc/nginx/sites-enabled/
CMD ["bash", "entry-point.sh"]