sonar.organization=aphp
sonar.projectKey=aphp_Cohort360-AdministrationPortal
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=build/**,node_modules/**
sonar.qualitygate.wait=true
